# Generated by Django 5.2 on 2025-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_set_bigautofield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testenvironmentcategory',
            new_name='test_enviro_env_cat_1ab8f1_idx',
            old_fields=('env_category_id', 'product'),
        ),
        migrations.RenameIndex(
            model_name='testenvironmentcategory',
            new_name='test_enviro_product_d27c73_idx',
            old_fields=('product', 'name'),
        ),
    ]
