# Generated by Django 5.2 on 2025-04-13 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logs', '0004_set_bigautofield'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmslogmodel',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tcmslogmodel',
            name='object_pk',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='tcmslogmodel',
            index=models.Index(fields=['object_pk', 'content_type'], name='tcms_logs_object__2803fe_idx'),
        ),
    ]
