# Generated by Django 5.2 on 2025-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0011_remove_auto_now_add_from_plan_text_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testplan',
            new_name='test_plans_product_65852c_idx',
            old_fields=('product', 'plan_id'),
        ),
    ]
