# Generated by Django 5.2 on 2025-04-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('linkreference', '0002_set_bigautofield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linkreference',
            new_name='tcms_linkre_content_02d314_idx',
            old_fields=('content_type', 'object_pk', 'site'),
        ),
        migrations.AlterField(
            model_name='linkreference',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='linkreference',
            name='object_pk',
            field=models.TextField(null=True),
        ),
    ]
