# Generated by Django 5.2 on 2025-04-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testcases', '0012_set_bigautofield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='tcms_contac_content_93aa83_idx',
            old_fields=('content_type', 'object_pk', 'site'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
